language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
before_script:
  - npm install
script:
  - npm test
deploy:
  provider: script
  skip_cleanup: true
  script:
    - chmod +x ./deploy.sh && ./deploy.sh
  on:
    branch: master
